### ISSUE TITLE
doesn't load on 1.12 Spigot

### ISSUE THREAD

**Issue by Jay9519** [MyWarp/MyWarp#149]
[19:45:47] [Server thread/ERROR]: Could not load 'plugins/mywarp-bukkit-3.0-beta-4-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/Logger;
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-latest.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:326) ~[spigot-latest.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-latest.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:302) [spigot-latest.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-latest.jar:git-Spigot-cd6ba67-f7d14f1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-latest.jar:git-Spigot-cd6ba67-f7d14f1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/Logger;
	at me.taylorkelly.mywarp.internal.slf4j.helpers.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:53) ~[?:?]
	at me.taylorkelly.mywarp.internal.slf4j.LoggerFactory.getLogger(LoggerFactory.java:285) ~[?:?]
	at me.taylorkelly.mywarp.internal.slf4j.LoggerFactory.getLogger(LoggerFactory.java:305) ~[?:?]
	at me.taylorkelly.mywarp.util.MyWarpLogger.<init>(MyWarpLogger.java:43) ~[?:?]
	at me.taylorkelly.mywarp.util.MyWarpLogger.getLogger(MyWarpLogger.java:54) ~[?:?]
	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.<clinit>(MyWarpPlugin.java:84) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-latest.jar:git-Spigot-cd6ba67-f7d14f1]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-latest.jar:git-Spigot-cd6ba67-f7d14f1]
	... 6 more

**Comment by TheE** [comment]
Use the latest devBuild.
