### ISSUE TITLE
error on /warp info xyz

### ISSUE THREAD

**Issue by kaiarne** [MyWarp/MyWarp#153]
When using /warp info [warpname] we get an internal server error. We don't use this command very often, so I can't tell exactly when this stopped working - I did "zgrep" on our logfiles I found it working back in late May (before 1.12). Our Server has been using early versions of mywarp since 2011, so thanks alot for updating it still so many years later!

```
[10:43:15 ERROR]: [MyWarp] The command 'warp info myhome' could not be executed.
io.github.mywarp.mywarp.internal.intake.InvocationCommandException: Cannot format given Object as a Date
        at io.github.mywarp.mywarp.internal.intake.parametric.AbstractParametricCallable.call(AbstractParametricCallable.java:230)
        at io.github.mywarp.mywarp.internal.intake.dispatcher.SimpleDispatcher.execute(SimpleDispatcher.java:192)
        at io.github.mywarp.mywarp.internal.intake.dispatcher.SimpleDispatcher.call(SimpleDispatcher.java:175)
        at io.github.mywarp.mywarp.internal.intake.dispatcher.SimpleDispatcher.execute(SimpleDispatcher.java:192)
        at io.github.mywarp.mywarp.internal.intake.dispatcher.SimpleDispatcher.call(SimpleDispatcher.java:175)
        at io.github.mywarp.mywarp.command.CommandHandler.callCommand(CommandHandler.java:193)
        at io.github.mywarp.mywarp.bukkit.MyWarpPlugin.onCommand(MyWarpPlugin.java:205)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:630)
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Cannot format given Object as a Date
        at java.text.DateFormat.format(DateFormat.java:310)
        at java.text.Format.format(Format.java:157)
        at io.github.mywarp.mywarp.command.util.printer.InfoPrinter.getText(InfoPrinter.java:151)
        at io.github.mywarp.mywarp.command.util.printer.InfoPrinter.print(InfoPrinter.java:170)
        at io.github.mywarp.mywarp.command.InformativeCommands.info(InformativeCommands.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.github.mywarp.mywarp.internal.intake.parametric.MethodCallable.call(MethodCallable.java:66)
        at io.github.mywarp.mywarp.internal.intake.parametric.AbstractParametricCallable$1.call(AbstractParametricCallable.java:209)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
        at io.github.mywarp.mywarp.internal.intake.parametric.ParametricBuilder$DirectExecutorService.execute(ParametricBuilder.java:277)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
        at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:36)
        at io.github.mywarp.mywarp.internal.intake.parametric.CommandExecutorWrapper.submit(CommandExecutorWrapper.java:44)
        at io.github.mywarp.mywarp.internal.intake.parametric.AbstractParametricCallable.call(AbstractParametricCallable.java:206)
        ... 15 more
```

**Comment by TheE** [comment]
Should be fixed in the latest devBuild. Thanks for reporting the issue.
