### ISSUE TITLE
1710 Not Work?

### ISSUE THREAD

**Issue by fickyu** [MyWarp/MyWarp#161]
```
 [Minecraft/]: Error occurred while enabling MyWarp v3.0-SNAPSHOT+jenkins-b176.git-3126cab9ba (Is it up to date?)
java.lang.NoClassDefFoundError: io/github/mywarp/mywarp/warp/storage/generated/tables/Group
	at io.github.mywarp.mywarp.warp.storage.generated.Tables.<clinit>(Tables.java:46) ~[?:?]
	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.createSettings(WarpStorageFactory.java:119) ~[?:?]
	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.createInitialized(WarpStorageFactory.java:108) ~[?:?]
	at io.github.mywarp.mywarp.MyWarp.initialize(MyWarp.java:110) ~[?:?]
	at io.github.mywarp.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:116) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.55]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1614.55]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1614.55]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:513) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:487) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:447) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: Failed to remap class io.github.mywarp.mywarp.warp.storage.generated.tables.Group
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:489) ~[PluginClassLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:410) ~[PluginClassLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.55]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 16 more
Caused by: java.lang.NoClassDefFoundError: io/github/mywarp/mywarp/internal/jooq/impl/TableImpl
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_131]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_131]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:477) ~[PluginClassLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:410) ~[PluginClassLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.55]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 16 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class io.github.mywarp.mywarp.internal.jooq.impl.TableImpl
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:489) ~[PluginClassLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:410) ~[PluginClassLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.55]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_131]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_131]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:477) ~[PluginClassLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:410) ~[PluginClassLoader.class:1.7.10-1614.55]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.55]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 16 more
```

**Comment by TheE** [comment]
This looks like a (strange) problem within JOOQ which was updated to 3.9.5 with build 176. Could you please answer the following questions:

1. What version of Java are you using?
2. What version of Minecraft?
3. What version of Spigot/CraftBukkit?
4. Was any of the previous builds working without problems?

**Comment by TheE** [comment]
This is very strange. Unfortunately I can only take a closer look at this in about twee weeks, so until then please use the latest working build (175 I assume?).

**Comment by TheE** [comment]
I cannot reproduce this. Did you maybe use `/reload` when updating MyWarp instead of restarting the server?
