### ISSUE TITLE
Error Installing...

### ISSUE THREAD

**Issue by Xapurass** [MyWarp/MyWarp#172]
Getting this after restarting the server and trying to set a warp...

[09:38:59 INFO]: Xxxxxxxx issued server command: /warp set MyWarp
[09:38:59 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warp' in plugin MyWarp v2.6.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-bde2a93]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-bde2a93]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:627) ~[craftbukkit.jar:git-Bukkit-bde2a93]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1327) [craftbukkit.jar:git-Bukkit-bde2a93]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1187) [craftbukkit.jar:git-Bukkit-bde2a93]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-bde2a93]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-bde2a93]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-bde2a93]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Bukkit-bde2a93]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit.jar:git-Bukkit-bde2a93]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit.jar:git-Bukkit-bde2a93]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit.jar:git-Bukkit-bde2a93]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit.jar:git-Bukkit-bde2a93]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at me.taylorkelly.mywarp.MyWarp.onCommand(MyWarp.java:221) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-bde2a93]
        ... 15 more

ThanX!

**Comment by TheE** [comment]
If you are running anything newer than Minecraft 1.7.2, you must use one of the [3.0 betas](https://dev.bukkit.org/projects/mywarp/files/2386565). For 1.12, please use a [development build](https://thee140.ci.cloudbees.com/job/MyWarp%203%20(for%20Bukit%201.7.9.+)/).

MyWarp 3 is the only version that supports recent versions of Minecraft and Bukkit. They are just labeled 'beta' because I still need to implement several internal changes in preparation of the Sponge version. For end-users they are pretty stable.

**Comment by Xapurass** [comment]
ThanX - New to all of this :(

**Comment by Xapurass** [comment]
OK ... all better now ;)  

Question:  When creating signs, the [MyWarp] is NOT displayed in color (like we see on other server signs). 
Is this in the works (not in dev build yet) -or- is something wrong/needed to be configured?

**Comment by TheE** [comment]
No, this is intended behavior, MyWarp's signs are not colored in any way.

I have done this because colored sign text is not really covered by the Bukit or Sponge; it works by writing some characters on the sign that clients display as color. Given that Minecraft is moving away from the old chat color (`§r` etc.) it cannot be guaranteed that colored signs will continue to work in future versions.
