### ISSUE TITLE
Exception thrown on plugin enable / server start-up

### ISSUE THREAD

**Issue by Bujiraso** [MyWarp/MyWarp#180]
### Environment
```
$ uname -a
Linux Juniper 4.15.3-2-ARCH #1 SMP PREEMPT Thu Feb 15 00:13:49 UTC 2018 x86_64 GNU/Linux
```

```
$ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```
```
$ pacaur -Qs craftbukkit
local/craftbukkit-spigot 1.12.2-2
    CraftBukkit & Spigot Minecraft servers
```
Using Craftbukkit

### Steps to Reproduce
1. Download jar into /srv/craftbukkit/plugins
2. Restart craftbukkit

### Expected
Plugin works as described

### Actual
Plugin throws exception complaining about NoSuchMethodError, calling (old?) Bukkit APIs

### Stack Trace
```
[09:52:37] [Server thread/ERROR]: Error occurred while enabling MyWarp v2.6.5 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at me.taylorkelly.mywarp.WarpSettings.<init>(WarpSettings.java:98) ~[?:?]
        at me.taylorkelly.mywarp.MyWarp.onEnable(MyWarp.java:255) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Bukkit-015bda4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-015bda4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Bukkit-015bda4]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [craftbukkit.jar:git-Bukkit-015bda4]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [craftbukkit.jar:git-Bukkit-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit.jar:git-Bukkit-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit.jar:git-Bukkit-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit.jar:git-Bukkit-015bda4]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit.jar:git-Bukkit-015bda4]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit.jar:git-Bukkit-015bda4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by Bujiraso** [comment]
```
$ ./send_command.sh version
>version
This server is running CraftBukkit version git-Bukkit-015bda4 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Checking version, please wait...
```

**Comment by TheE** [comment]
Strange, what does `/version mywarp` print?

**Comment by Bujiraso** [comment]
```
$ ./send_command.sh "version mywarp"
>version mywarp
�MyWarp� version �2.6.5
Provides the ability to create private and public warp points that can be shared with other players in various ways.
Website: �http://dev.bukkit.org/server-mods/mywarp/
Authors: �tkelly�, �flames�, �spathizilla�, �mung3r� and �thee
```

I got it from the Bukkit site, maybe it's the wrong jar?

**Comment by TheE** [comment]
Yes, version 2.6.5 only works with Bukkit till version  1.7.2. For anything newer you have to use the 3.0 beta. It is extremely stable and just labeled beta because I still have no make some internal changes to add support for Sponge (and hardly find the time to do so).

Generally the beta versions on BukkitDev are fine, but for 1.12 you have to use a [devBuild](https://thee140.ci.cloudbees.com/job/MyWarp%203%20(for%20Bukit%201.7.9.+)/).

**Comment by Bujiraso** [comment]
Dev build works great. 
Thanks

P.S. Might be good to "h1." and red the note on that page about 1.12!
