### ISSUE TITLE
Loading a dev build for 1.14.2 Spigot

### ISSUE THREAD

**Issue by Jay9519** [MyWarp/MyWarp#214]
### Description of the Problem
Won't load on server startup

### Log Output
```
[09:37:43] [Server thread/ERROR]: Could not load 'plugins\mywarp-bukkit-3.0.2-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: io/github/mywarp/mywarp/util/i18n/FolderSourcedControl
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333) ~[spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:347) [spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoClassDefFoundError: io/github/mywarp/mywarp/util/i18n/FolderSourcedControl
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	... 6 more
Caused by: java.lang.ClassNotFoundException: io.github.mywarp.mywarp.util.i18n.FolderSourcedControl
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-latest.jar:git-Spigot-df0eb25-da071ec]
	... 6 more
````

### Affected Version
````
mywarp-bukkit-3.0.2-SNAPSHOT.jar
1.14.2-R0.1-SNAPSHOT
````

**Comment by TheE** [comment]
You downloaded the wrong JAR-file, you need `mywarp-bukkit-3.0.2-SNAPSHOT-all.jar` which contains all required dependencies.
