### ISSUE TITLE
[Bug] Not working on Craftbukkit 1.14.4

### ISSUE THREAD

**Issue by Maelep** [MyWarp/MyWarp#216]
### Description of the Problem
Not working on CraftBukkit 1.14.4

### Steps to Reproduce
Install the plugins and launch the server.

### Log Output
```
[05:17:08] [Server thread/INFO]: [MyWarp] Enabling MyWarp v3.0.1+travis-b1776.git-351e1d5c00
[05:17:08] [Thread-6/INFO]: [ClearLag] Checking for updates compatible with your bukkit version [1.14]...
[05:17:10] [Thread-6/INFO]: [ClearLag] No updates found!
[05:17:13] [Server thread/INFO]: io.github.mywarp.mywarp.internal.h2.message.DbException: (Message 90034 not found) [90034-197]
[05:17:13] [Server thread/WARN]: io.github.mywarp.mywarp.internal.h2.message.DbException: (Message 90034 not found) [90034-197]
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:168)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.logWritingError(TraceSystem.java:289)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.openWriter(TraceSystem.java:310)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.writeFile(TraceSystem.java:258)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.write(TraceSystem.java:242)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.Trace.error(Trace.java:196)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Database.openDatabase(Database.java:314)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Database.<init>(Database.java:280)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:66)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:179)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:140)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:28)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.Driver.connect(Driver.java:69)
[05:17:13] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
[05:17:13] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.initiate(SingleConnectionDataSource.java:163)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:83)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.<init>(WarpStorageFactory.java:64)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.createAndInitialize(WarpStorageFactory.java:105)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.MyWarp.initialize(MyWarp.java:110)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:114)
[05:17:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:17:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344)
[05:17:13] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
[05:17:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:447)
[05:17:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:373)
[05:17:13] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
[05:17:13] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:243)
[05:17:13] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:754)
[05:17:13] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[05:17:13] [Server thread/WARN]: Caused by: io.github.mywarp.mywarp.internal.h2.jdbc.JdbcSQLException: (Message 90034 not found) [90034-197]
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:357)
[05:17:13] [Server thread/WARN]: 	... 34 more
[05:17:13] [Server thread/WARN]: Caused by: io.github.mywarp.mywarp.internal.h2.message.DbException: (Message 90062 not found) [90062-197]
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:179)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:155)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:271)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectory(FileUtils.java:42)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:312)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.openWriter(TraceSystem.java:300)
[05:17:13] [Server thread/WARN]: 	... 31 more
[05:17:13] [Server thread/WARN]: Caused by: io.github.mywarp.mywarp.internal.h2.jdbc.JdbcSQLException: (Message 90062 not found) [90062-197]
[05:17:13] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:357)
[05:17:13] [Server thread/WARN]: 	... 45 more
[05:17:13] [Server thread/ERROR]: [MyWarp] [0;31;1mFailed to initialize warp storage.
io.github.mywarp.mywarp.warp.storage.StorageInitializationException: Connection failed due to an SQLException. Is the configuration valid?
	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.<init>(WarpStorageFactory.java:72)
	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.createAndInitialize(WarpStorageFactory.java:105)
	at io.github.mywarp.mywarp.MyWarp.initialize(MyWarp.java:110)
	at io.github.mywarp.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:114)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:447)
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:373)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:243)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:754)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.github.mywarp.mywarp.internal.h2.jdbc.JdbcSQLException: (Message 90062 not found) [90062-197]
	at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:179)
	at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:155)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:271)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectory(FileUtils.java:42)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:312)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:311)
	at io.github.mywarp.mywarp.internal.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:74)
	at io.github.mywarp.mywarp.internal.h2.engine.Database.getPageStore(Database.java:2538)
	at io.github.mywarp.mywarp.internal.h2.engine.Database.open(Database.java:709)
	at io.github.mywarp.mywarp.internal.h2.engine.Database.openDatabase(Database.java:286)
	at io.github.mywarp.mywarp.internal.h2.engine.Database.<init>(Database.java:280)
	at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:66)
	at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:179)
	at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:140)
	at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:28)
	at io.github.mywarp.mywarp.internal.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at io.github.mywarp.mywarp.internal.h2.Driver.connect(Driver.java:69)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.initiate(SingleConnectionDataSource.java:163)
	at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:83)
	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.<init>(WarpStorageFactory.java:64)
	... 12 more[m
[05:17:13] [Server thread/ERROR]: [MyWarp] [0;31;1mMyWarp is unable to continue and will be disabled.[m
[05:17:13] [Server thread/INFO]: [MyWarp] Disabling MyWarp v3.0.1+travis-b1776.git-351e1d5c00
```

### Affected Version
* MyWarp: ` MyWarp v3.0.1 `
* Minecraft and Bukkit Implementation: `Craftbukkit-1.14.4-R0.1-SNAPSHOT.jar `

**Comment by Nykoload** [comment]
I believe you have the incorrect .jar file, try using the one labeled "mywarp-bukkit-3.0.2-SNAPSHOT-all.jar" found at https://mywarp.github.io/builds/1785.html

Found this whilst looking into an alternate issue myself, so hopefully this is helpful for someone.

**Comment by TheE** [comment]
I cannot reproduce this. Could you try it again using the the `-all` jar from the [most recent build](https://mywarp.github.io/builds/1788.html) as @Nykoload mentioned?
