### ISSUE TITLE
[Bug] JdbcSQLNonTransientException: (Message 90062 not found)

### ISSUE THREAD

**Issue by Nextros** [MyWarp/MyWarp#245]
Hello, when I start my server, it says this. It never happend before and I don't know what to do. Is there any solution?

```
[ERROR] [MyWarp] Failed to initialize warp storage.
[ERROR] [MyWarp] (Message 90062 not found) [90062-200]
io.github.mywarp.mywarp.internal.h2.jdbc.JdbcSQLNonTransientException: (Message 90062 not found) [90062-200]
at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:505)
at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:429)
at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:205)
at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:181)
at io.github.mywarp.mywarp.internal.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:290)
at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43)
at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:315)
at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
at io.github.mywarp.mywarp.internal.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:73)
at io.github.mywarp.mywarp.internal.h2.engine.Database.getPageStore(Database.java:2659)
at io.github.mywarp.mywarp.internal.h2.engine.Database.open(Database.java:675)
at io.github.mywarp.mywarp.internal.h2.engine.Database.openDatabase(Database.java:307)
at io.github.mywarp.mywarp.internal.h2.engine.Database.<init>(Database.java:301)
at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:74)
at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:192)
at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:166)
at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:29)
at io.github.mywarp.mywarp.internal.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
at io.github.mywarp.mywarp.internal.h2.Driver.connect(Driver.java:69)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:208)
at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.initiate(SingleConnectionDataSource.java:163)
at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:83)
at io.github.mywarp.mywarp.warp.storage.WarpStorageBuilder.build(WarpStorageBuilder.java:150)
at io.github.mywarp.mywarp.MyWarp.initialize(MyWarp.java:116)
at io.github.mywarp.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:116)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
at java.lang.Thread.run(Thread.java:813)
[ERROR] [MyWarp] MyWarp is unable to continue and will be disabled.
```

**Comment by TheE** [comment]
According to the [documentation of H2](http://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90062), error `90062` indicates the the database file could not be created. Are you sure that the database file within MyWarp's plugin directory is writable?

Could you try to move the database files (normally called `warps.h2.db`) from MyWarp's plugin directory  to another directory? When you restart the server, MyWarp should create a fresh database. If this works, you might be able to import the warps from the old database.

If neither works, please provide the following information:
- What version of MyWarp are you using (`/version MyWarp`)?
- What version of Bukkit (`/version`)?
- Did you recently update MyWarp?
